import { StaffMember } from '../../types';

export const ALL_STAFF: StaffMember[] = [
  {
    id: 'staff-as',
    name: 'Dr. A. Suneetha',
    code: 'Dr. AS',
    email: 'principal@kvsrsiddharthapharma.edu.in',
    department: 'Pharmaceutical Analysis (Principal)',
    specialization: ['Pharmaceutical Analysis', 'Quality Assurance', 'Institutional Governance'],
    assignedSubjects: [],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-vk',
    name: 'Dr. V. Karuna Sree',
    code: 'Dr. VK',
    email: 'karunasree.v@siddartha.edu',
    department: 'Pharmacognosy',
    specialization: ['Pharmacognosy & Phytochemistry', 'Introduction to Pharmacognosy (P.Cog.)'],
    assignedSubjects: ['sub-pcog', 'sub-pcog-2'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-chnb',
    name: 'Dr. Ch. Nagabhushanam',
    code: 'Dr. CHNB',
    email: 'nagabhushanam.ch@siddartha.edu',
    department: 'Pharmacology',
    specialization: ['Human Anatomy & Physiology (HAP/HAPP)', 'Class Incharge'],
    assignedSubjects: ['sub-happ', 'sub-hap'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-krs',
    name: 'Dr. K. Ravi Shankar',
    code: 'Dr. KRS',
    email: 'ravishankar.k@siddartha.edu',
    department: 'Pharmaceutics',
    specialization: ['General Pharmacy (GP)', 'Pharmaceutics (PH)', 'NDDS', 'Class Incharge'],
    assignedSubjects: ['sub-gp', 'sub-ph', 'sub-ndds'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-skab',
    name: 'Dr. Sk. Arifa Begum',
    code: 'Dr. Sk.AB',
    email: 'arifabegum.sk@siddartha.edu',
    department: 'Pharmaceutics & Biochemistry',
    specialization: ['General Pharmacy', 'Biochemistry', 'Pharmaceutical Formulations (PF)'],
    assignedSubjects: ['sub-gp', 'sub-biochem', 'sub-pf', 'sub-bpk'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-ps',
    name: 'Dr. P. Swetha',
    code: 'Dr. PS',
    email: 'swetha.p@siddartha.edu',
    department: 'Pharmacognosy',
    specialization: ['Pharmacognosy & Phytopharmaceuticals (PPP/P.Cog.)', 'Class Incharge'],
    assignedSubjects: ['sub-pcog', 'sub-ppp', 'sub-pcog-2'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-tsm',
    name: 'Ms. T. Sarada Mrinalini',
    code: 'Ms. TSM',
    email: 'sarada.m@siddartha.edu',
    department: 'Pharmaceutical Chemistry',
    specialization: ['Pharmaceutical Inorganic & Analytical Chemistry (PIAC)'],
    assignedSubjects: ['sub-piac'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-rt',
    name: 'Dr. R. Triveni',
    code: 'Ms. RT',
    email: 'triveni.r@siddartha.edu',
    department: 'Hospital Pharmacy & Psychology',
    specialization: ['Healthcare Psychology', 'Hospital Pharmacy (HP)', 'Clinical Toxicology (CT)', 'Pharmacy Practice (PP)'],
    assignedSubjects: ['sub-psych', 'sub-hp', 'sub-ct', 'sub-pp-practice'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-chp',
    name: 'Ms. Ch. Pallavi',
    code: 'Ms. CH.P',
    email: 'pallavi.ch@siddartha.edu',
    department: 'Pharmaceutical Chemistry',
    specialization: ['Pharmaceutical Inorganic & Analytical Chemistry (PIAC/PIC)'],
    assignedSubjects: ['sub-piac', 'sub-pic'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-gs',
    name: 'Mr. G. Sridhar',
    code: 'Mr. GS',
    email: 'sridhar.g@siddartha.edu',
    department: 'Computer Sciences',
    specialization: ['Python Programming for Pharmaceutical Sciences'],
    assignedSubjects: ['sub-python'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-bnr',
    name: 'Dr. B. Naga Raju',
    code: 'Dr. BNR',
    email: 'nagaraju.b@siddartha.edu',
    department: 'Pharmacology',
    specialization: ['HAPP', 'Pharmacology-I (P. Col-I)', 'Class Incharge'],
    assignedSubjects: ['sub-happ', 'sub-pcol-1'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-gvk',
    name: 'Dr. G. Vijaya Kumar',
    code: 'Dr. GVK',
    email: 'vijayakumar.g@siddartha.edu',
    department: 'Pharmacy Practice & Psychology',
    specialization: ['Pharmacotherapeutics (PT-I/PT-II)', 'Psychology Lab', 'Ward Rounds'],
    assignedSubjects: ['sub-psych', 'sub-pt-1', 'sub-pt-2', 'sub-ward'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-psrinivasu',
    name: 'Mr. P. Srinivasu',
    code: 'Mr. PS',
    email: 'srinivasu.p@siddartha.edu',
    department: 'Pharmaceutics & Industrial Pharmacy',
    specialization: ['General Pharmacy (GP)', 'Industrial Pharmacy-I/II (IP-I/IP-II)', 'Physical Pharmaceutics (PP-I)'],
    assignedSubjects: ['sub-gp', 'sub-ip-1', 'sub-ip-2', 'sub-pp-1'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-tsd',
    name: 'Dr. T. Sarala Devi',
    code: 'Dr. TSD',
    email: 'saraladevi.t@siddartha.edu',
    department: 'Pharmaceutical Chemistry',
    specialization: ['Pharmaceutical Organic Chemistry (POC/POC-II)', 'Class Incharge'],
    assignedSubjects: ['sub-poc', 'sub-poc-2'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-vn',
    name: 'Dr. V. Narendra',
    code: 'Dr. VN',
    email: 'narendra.v@siddartha.edu',
    department: 'Pharmaceutical Chemistry',
    specialization: ['Pharmaceutical Organic Chemistry (POC/POC-II)', 'Medicinal Chemistry-II (MC-II)'],
    assignedSubjects: ['sub-poc', 'sub-poc-2', 'sub-mc-2'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-kak',
    name: 'Sri. K. Anil Kumar',
    code: 'Sri. KAK',
    email: 'anilkumar.k@siddartha.edu',
    department: 'Pharmaceutics & Engineering',
    specialization: ['Pharmaceutical Engineering (PE)', 'Pharmaceutics (PH)', 'Pharmaceutical Jurisprudence (PJ)'],
    assignedSubjects: ['sub-pe', 'sub-ph', 'sub-pj', 'sub-ip-2'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-mp',
    name: 'Mr. M. Prince',
    code: 'Mr. MP',
    email: 'prince.m@siddartha.edu',
    department: 'Medicinal Biochemistry',
    specialization: ['Medicinal Biochemistry (Biochem)'],
    assignedSubjects: ['sub-biochem'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-mvr',
    name: 'Smt. M. Venkata Ramana',
    code: 'Smt. MVR',
    email: 'venkataramana.m@siddartha.edu',
    department: 'Remedial Sciences',
    specialization: ['Remedial Mathematics / Biology'],
    assignedSubjects: ['sub-math-bio'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-nkd',
    name: 'Dr. N. Kanaka Durga Devi',
    code: 'Dr. NKD',
    email: 'kanakadurgadevi.n@siddartha.edu',
    department: 'Pharmaceutical Microbiology',
    specialization: ['Pharmaceutical Microbiology (PM)'],
    assignedSubjects: ['sub-pm'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-alp',
    name: 'Smt. A. Lakshmi Pavani',
    code: 'Smt. ALP',
    email: 'lakshmipavani.a@siddartha.edu',
    department: 'Pharmacy Practice',
    specialization: ['Pathophysiology (PP)', 'Community Pharmacy (CP)', 'Clinical Pharmacy', 'Class Incharge'],
    assignedSubjects: ['sub-patho', 'sub-cp', 'sub-clinical-pharm'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-ghs',
    name: 'Smt. G. Hema Sree',
    code: 'Smt. GHS',
    email: 'hemasree.g@siddartha.edu',
    department: 'Pharmacology',
    specialization: ['Pharmacology-I/II (P. Col-I/P. Col-II)', 'Class Incharge'],
    assignedSubjects: ['sub-pcol-1', 'sub-pcol-2'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-ks',
    name: 'Dr. K. Sirisha',
    code: 'Dr. KS',
    email: 'sirisha.k@siddartha.edu',
    department: 'Pharmacy Practice',
    specialization: ['Pharmacotherapeutics (PT-II)', 'Clinical Toxicology', 'Class Incharge'],
    assignedSubjects: ['sub-pt-2', 'sub-ct', 'sub-case-pres'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-ku',
    name: 'Dr. K. Umamaheswari',
    code: 'Dr. KU',
    email: 'umamaheswari.k@siddartha.edu',
    department: 'Pharmaceutical Microbiology',
    specialization: ['Pharmaceutical Microbiology (PM)', 'Class Incharge'],
    assignedSubjects: ['sub-pm'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-gr',
    name: 'Dr. G. Ramana',
    code: 'Dr. GR',
    email: 'ramana.g@siddartha.edu',
    department: 'Pharmaceutics & Formulations',
    specialization: ['Pharmaceutical Formulations (PF)', 'Novel Drug Delivery System (NDDS)'],
    assignedSubjects: ['sub-pf', 'sub-ndds'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-mvl',
    name: 'Dr. M. Vijaya Lakshmi',
    code: 'Dr. MVL',
    email: 'vijayalakshmi.m@siddartha.edu',
    department: 'Pharmaceutical Analysis',
    specialization: ['Pharmaceutical Analysis (PA)'],
    assignedSubjects: ['sub-pa'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-ba',
    name: 'Dr. B. Anupama',
    code: 'Dr. BA',
    email: 'anupama.b@siddartha.edu',
    department: 'Medicinal Chemistry',
    specialization: ['Medicinal Chemistry (MC)'],
    assignedSubjects: ['sub-mc'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-cs',
    name: 'Dr. Ch. Supriya',
    code: 'Dr. CHS',
    email: 'supriya.ch@siddartha.edu',
    department: 'Pharmacology',
    specialization: ['Pharmacology-II/III (P. Col-II/P. Col-III)'],
    assignedSubjects: ['sub-pcol-2', 'sub-pcol-3'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-tvs',
    name: 'Sri. T.V. Subba Rao',
    code: 'Dr. TVS',
    email: 'subbarao.tv@siddartha.edu',
    department: 'Pharmacology',
    specialization: ['Pharmacology-II (P. Col-II)'],
    assignedSubjects: ['sub-pcol-2'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-kp',
    name: 'Dr. K. Pradeepthi',
    code: 'Dr. KP',
    email: 'pradeepthi.k@siddartha.edu',
    department: 'Clinical Pharmacy',
    specialization: ['Clinical Pharmacy (CP)', 'PEPE', 'Class Incharge'],
    assignedSubjects: ['sub-cp', 'sub-pepe'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-grs',
    name: 'Dr. G. Ramya Sri',
    code: 'Dr. GRS',
    email: 'ramyasri.g@siddartha.edu',
    department: 'Pharmacotherapeutics & TDM',
    specialization: ['Pharmacotherapeutics-III (PT-III)', 'Therapeutic Drug Monitoring (TDM)'],
    assignedSubjects: ['sub-pt-3', 'sub-tdm'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-kvs',
    name: 'Dr. K. Viswa Srujani',
    code: 'Dr. KVS',
    email: 'viswasrujani.k@siddartha.edu',
    department: 'Clinical Research & Biostatistics',
    specialization: ['Clinical Research (CR)', 'Biostatistics & Research Methodology (BRM)', 'Class Incharge'],
    assignedSubjects: ['sub-cr', 'sub-brm'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-ab',
    name: 'Dr. A. Bharathi',
    code: 'Dr. AB',
    email: 'bharathi.a@siddartha.edu',
    department: 'Pharmaceutics & Biopharmaceutics',
    specialization: ['Biopharmaceutics & Pharmacokinetics (BPK)', 'Physical Pharmaceutics-I (PP-I)'],
    assignedSubjects: ['sub-bpk', 'sub-pp-1'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-kdp',
    name: 'Mr. K. Durga Prasad',
    code: 'Mr. KDP',
    email: 'durgaprasad.k@siddartha.edu',
    department: 'Pharmaceutical Chemistry',
    specialization: ['Pharmaceutical Organic Chemistry-II (POC-II)'],
    assignedSubjects: ['sub-poc-2'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-ra',
    name: 'Smt. R. Anusha',
    code: 'Smt. RA',
    email: 'anusha.r@siddartha.edu',
    department: 'Physical Pharmaceutics',
    specialization: ['Physical Pharmaceutics-I (PP-I)', 'Class Incharge'],
    assignedSubjects: ['sub-pp-1'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-rl',
    name: 'Smt. R. Lakshmi',
    code: 'Smt. RL',
    email: 'lakshmi.r@siddartha.edu',
    department: 'Medicinal & Organic Chemistry',
    specialization: ['Medicinal Chemistry-II (MC-II)', 'POC-II Lab', 'Class Incharge'],
    assignedSubjects: ['sub-mc-2', 'sub-poc-2'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-psravanthi',
    name: 'Smt. P. Sravanthi',
    code: 'Smt. PS',
    email: 'sravanthi.p@siddartha.edu',
    department: 'Pharmaceutics & Jurisprudence',
    specialization: ['Pharmaceutical Engineering (PE)', 'Pharmaceutical Jurisprudence (PJ)', 'Class Incharge'],
    assignedSubjects: ['sub-pe', 'sub-pj'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-tpr',
    name: 'Dr. T.P. Rao',
    code: 'Dr. TPR',
    email: 'tprao@siddartha.edu',
    department: 'Industrial Pharmacy & Engineering',
    specialization: ['Industrial Pharmacy-I (IP-I)', 'Pharmaceutical Engineering (PE)'],
    assignedSubjects: ['sub-ip-1', 'sub-pe'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-kshanmukhi',
    name: 'Ms. K. Shanmukhi',
    code: 'Ms. KS',
    email: 'shanmukhi.k@siddartha.edu',
    department: 'Pharmaceutical Jurisprudence',
    specialization: ['Pharmaceutical Jurisprudence (PJ)', 'Class Incharge'],
    assignedSubjects: ['sub-pj'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-khb',
    name: 'Dr. K. Hari Babu',
    code: 'Dr. KHB',
    email: 'haribabu.k@siddartha.edu',
    department: 'Pharmaceutical Analysis',
    specialization: ['Instrument Methods of Analysis (IMA)'],
    assignedSubjects: ['sub-ima'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-kj',
    name: 'Smt. K. Jyothi',
    code: 'Smt. KJ',
    email: 'jyothi.k@siddartha.edu',
    department: 'Pharmaceutical Analysis',
    specialization: ['Instrument Methods of Analysis (IMA)', 'Class Incharge'],
    assignedSubjects: ['sub-ima'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  {
    id: 'staff-kramya',
    name: 'Smt. K. Ramya Sri',
    code: 'Smt. RS',
    email: 'ramyasri.k@siddartha.edu',
    department: 'Pharmacy Practice',
    specialization: ['Pharmacy Practice (PP)'],
    assignedSubjects: ['sub-pp-practice'],
    isActive: true,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  }
];
